services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret

  mongodb:
    image: mongo
    ports:
      - 27017:27017