/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vw.consent.management.system.kafka_model.avro.dto;
@org.apache.avro.specific.AvroGenerated
public enum ConsentType implements org.apache.avro.generic.GenericEnumSymbol<ConsentType> {
  EMAIL_NOTIFICATIONS, SMS_NOTIFICATIONS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConsentType\",\"namespace\":\"com.vw.consent.management.system.kafka_model.avro.dto\",\"symbols\":[\"EMAIL_NOTIFICATIONS\",\"SMS_NOTIFICATIONS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
