/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vw.consent.management.system.kafka_model.avro.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ConsentChangeEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1271245173500536405L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConsentChangeEvent\",\"namespace\":\"com.vw.consent.management.system.kafka_model.avro.dto\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"consentType\",\"type\":{\"type\":\"enum\",\"name\":\"ConsentType\",\"symbols\":[\"EMAIL_NOTIFICATIONS\",\"SMS_NOTIFICATIONS\"]}},{\"name\":\"enabled\",\"type\":\"boolean\"},{\"name\":\"eventTimestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ConsentChangeEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConsentChangeEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ConsentChangeEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ConsentChangeEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ConsentChangeEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ConsentChangeEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ConsentChangeEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ConsentChangeEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ConsentChangeEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userId;
  private java.lang.CharSequence email;
  private com.vw.consent.management.system.kafka_model.avro.dto.ConsentType consentType;
  private boolean enabled;
  private java.time.Instant eventTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConsentChangeEvent() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param email The new value for email
   * @param consentType The new value for consentType
   * @param enabled The new value for enabled
   * @param eventTimestamp The new value for eventTimestamp
   */
  public ConsentChangeEvent(java.lang.CharSequence userId, java.lang.CharSequence email, com.vw.consent.management.system.kafka_model.avro.dto.ConsentType consentType, java.lang.Boolean enabled, java.time.Instant eventTimestamp) {
    this.userId = userId;
    this.email = email;
    this.consentType = consentType;
    this.enabled = enabled;
    this.eventTimestamp = eventTimestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return email;
    case 2: return consentType;
    case 3: return enabled;
    case 4: return eventTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: consentType = (com.vw.consent.management.system.kafka_model.avro.dto.ConsentType)value$; break;
    case 3: enabled = (java.lang.Boolean)value$; break;
    case 4: eventTimestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'consentType' field.
   * @return The value of the 'consentType' field.
   */
  public com.vw.consent.management.system.kafka_model.avro.dto.ConsentType getConsentType() {
    return consentType;
  }


  /**
   * Sets the value of the 'consentType' field.
   * @param value the value to set.
   */
  public void setConsentType(com.vw.consent.management.system.kafka_model.avro.dto.ConsentType value) {
    this.consentType = value;
  }

  /**
   * Gets the value of the 'enabled' field.
   * @return The value of the 'enabled' field.
   */
  public boolean getEnabled() {
    return enabled;
  }


  /**
   * Sets the value of the 'enabled' field.
   * @param value the value to set.
   */
  public void setEnabled(boolean value) {
    this.enabled = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return The value of the 'eventTimestamp' field.
   */
  public java.time.Instant getEventTimestamp() {
    return eventTimestamp;
  }


  /**
   * Sets the value of the 'eventTimestamp' field.
   * @param value the value to set.
   */
  public void setEventTimestamp(java.time.Instant value) {
    this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new ConsentChangeEvent RecordBuilder.
   * @return A new ConsentChangeEvent RecordBuilder
   */
  public static com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder newBuilder() {
    return new com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder();
  }

  /**
   * Creates a new ConsentChangeEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConsentChangeEvent RecordBuilder
   */
  public static com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder newBuilder(com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder other) {
    if (other == null) {
      return new com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder();
    } else {
      return new com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder(other);
    }
  }

  /**
   * Creates a new ConsentChangeEvent RecordBuilder by copying an existing ConsentChangeEvent instance.
   * @param other The existing instance to copy.
   * @return A new ConsentChangeEvent RecordBuilder
   */
  public static com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder newBuilder(com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent other) {
    if (other == null) {
      return new com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder();
    } else {
      return new com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ConsentChangeEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConsentChangeEvent>
    implements org.apache.avro.data.RecordBuilder<ConsentChangeEvent> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence email;
    private com.vw.consent.management.system.kafka_model.avro.dto.ConsentType consentType;
    private boolean enabled;
    private java.time.Instant eventTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.consentType)) {
        this.consentType = data().deepCopy(fields()[2].schema(), other.consentType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.enabled)) {
        this.enabled = data().deepCopy(fields()[3].schema(), other.enabled);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[4].schema(), other.eventTimestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ConsentChangeEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.consentType)) {
        this.consentType = data().deepCopy(fields()[2].schema(), other.consentType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.enabled)) {
        this.enabled = data().deepCopy(fields()[3].schema(), other.enabled);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[4].schema(), other.eventTimestamp);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'consentType' field.
      * @return The value.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentType getConsentType() {
      return consentType;
    }


    /**
      * Sets the value of the 'consentType' field.
      * @param value The value of 'consentType'.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder setConsentType(com.vw.consent.management.system.kafka_model.avro.dto.ConsentType value) {
      validate(fields()[2], value);
      this.consentType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'consentType' field has been set.
      * @return True if the 'consentType' field has been set, false otherwise.
      */
    public boolean hasConsentType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'consentType' field.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder clearConsentType() {
      consentType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled' field.
      * @return The value.
      */
    public boolean getEnabled() {
      return enabled;
    }


    /**
      * Sets the value of the 'enabled' field.
      * @param value The value of 'enabled'.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder setEnabled(boolean value) {
      validate(fields()[3], value);
      this.enabled = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled' field has been set.
      * @return True if the 'enabled' field has been set, false otherwise.
      */
    public boolean hasEnabled() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'enabled' field.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder clearEnabled() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * @return The value.
      */
    public java.time.Instant getEventTimestamp() {
      return eventTimestamp;
    }


    /**
      * Sets the value of the 'eventTimestamp' field.
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder setEventTimestamp(java.time.Instant value) {
      validate(fields()[4], value);
      this.eventTimestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * @return This builder.
      */
    public com.vw.consent.management.system.kafka_model.avro.dto.ConsentChangeEvent.Builder clearEventTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConsentChangeEvent build() {
      try {
        ConsentChangeEvent record = new ConsentChangeEvent();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.consentType = fieldSetFlags()[2] ? this.consentType : (com.vw.consent.management.system.kafka_model.avro.dto.ConsentType) defaultValue(fields()[2]);
        record.enabled = fieldSetFlags()[3] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[3]);
        record.eventTimestamp = fieldSetFlags()[4] ? this.eventTimestamp : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConsentChangeEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConsentChangeEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConsentChangeEvent>
    READER$ = (org.apache.avro.io.DatumReader<ConsentChangeEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










